### ISSUE TITLE
Make a card receiver in the cashmachine

### ISSUE THREAD

**Issue by wwwal2** [Varkh/CashMachine-JS-Emulator#57]
We need an opening for a cards to put in. Let us call it RECEIVER. I think it should glow or blinking on a cash machine to see it better.

**Comment by Varkh** [comment]
It's called `CardReader`, see `CardReaderView`.
Lest start from simple:
- Add DIV with static height-width
- Implement drag-and-drop

**Comment by wwwal2** [comment]
OK
