### ISSUE TITLE
ShowButtons method to DisplayView

### ISSUE THREAD

**Issue by Varkh** [Varkh/CashMachine-JS-Emulator#60]
Add new method `showButtons` to DisplayView
It should display buttons titles on display. 8 titles near each button

- showButtons(text, buttonsArray)
    * text in the middle of screen
    * buttonsArray - list of 8 items ["title1", "title2", ..., null, "title8"]

**Comment by kds1660** [comment]
create function  createMenu(val,append), val= ['val1'...'val8'], append (true/false) - append to text display or delete display and view menu . I can change - add title for menu function , or use this without changes - append=true for create message and append table to it

**Comment by Varkh** [comment]
Done
