### ISSUE TITLE
Implement drag-and-drop for cards

### ISSUE THREAD

**Issue by Varkh** [Varkh/CashMachine-JS-Emulator#68]

**Comment by juliakukuliak** [comment]
Денис, привет. Нужно добавлять инпуты для ввода номера карты и даты? Или
просто оставить инпут только для ввода названия?(Извини, что так поздно)

2016-12-07 22:50 GMT+02:00 Denys <notifications@github.com>:

**Comment by kds1660** [comment]
там в issues https://github.com/Varkh/CashMachine-JS-Emulator/issues/26 денис писал 
Form for card creation
Name: ___
Balans: ___
Exp date: ___
PIN: ___
Create

**Comment by juliakukuliak** [comment]
Оо, спасибо)
08.12.2016 23:13 пользователь "kds1660" <notifications@github.com> написал:

**Comment by Varkh** [comment]
#26 делает Дима Шаповалов
Тебе нужно сделать драг&дроп
Сами карточки уже есть. А Дима должен был форму сделать. Спроси еще у него.

**Comment by Varkh** [comment]
Done
